//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:profile-Bar:2009")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:profile-Bar:2009", IsNullable=false)]
public partial class BarProfile {
    
    private UIColors uIColorsField;
    
    private string timeoutField;
    
    private bool freeOfChargeField;
    
    /// <remarks/>
    public UIColors UIColors {
        get {
            return this.uIColorsField;
        }
        set {
            this.uIColorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Timeout {
        get {
            return this.timeoutField;
        }
        set {
            this.timeoutField = value;
        }
    }
    
    /// <remarks/>
    public bool FreeOfCharge {
        get {
            return this.freeOfChargeField;
        }
        set {
            this.freeOfChargeField = value;
        }
    }
}

