//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:profile-foo:2009")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:profile-foo:2009", IsNullable=false)]
public partial class FooProfile {
    
    private UIColors uIColorsField;
    
    private string timeoutField;
    
    private bool freeOfChargeField;
    
    /// <remarks/>
    public UIColors UIColors {
        get {
            return this.uIColorsField;
        }
        set {
            this.uIColorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Timeout {
        get {
            return this.timeoutField;
        }
        set {
            this.timeoutField = value;
        }
    }
    
    /// <remarks/>
    public bool FreeOfCharge {
        get {
            return this.freeOfChargeField;
        }
        set {
            this.freeOfChargeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:profile-base:2009")]
public partial class UIColors {
    
    private Color backGroundField;
    
    private Color tableBorderField;
    
    private Color tableFontField;
    
    private Color titleFontField;
    
    private Color bodyFontField;
    
    /// <remarks/>
    public Color BackGround {
        get {
            return this.backGroundField;
        }
        set {
            this.backGroundField = value;
        }
    }
    
    /// <remarks/>
    public Color TableBorder {
        get {
            return this.tableBorderField;
        }
        set {
            this.tableBorderField = value;
        }
    }
    
    /// <remarks/>
    public Color TableFont {
        get {
            return this.tableFontField;
        }
        set {
            this.tableFontField = value;
        }
    }
    
    /// <remarks/>
    public Color TitleFont {
        get {
            return this.titleFontField;
        }
        set {
            this.titleFontField = value;
        }
    }
    
    /// <remarks/>
    public Color BodyFont {
        get {
            return this.bodyFontField;
        }
        set {
            this.bodyFontField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:profile-base:2009")]
public enum Color {
    
    /// <remarks/>
    Black,
    
    /// <remarks/>
    White,
    
    /// <remarks/>
    Yellow,
    
    /// <remarks/>
    Blue,
    
    /// <remarks/>
    Red,
    
    /// <remarks/>
    Green,
    
    /// <remarks/>
    Cyan,
}
